spring.data.mongodb:
#  authentication-database: admin
#  username: root
#  password: root
  database: test
  port: 27017
  host: localhost

server:
  port: 8080

spring.application.name: BootMongo
server.context-path: /